# Polarized Trees — Benchmark, Demo, and Inference

This notebook has **two roles**:

- it is a simple end-to-end example of how to use `PolarizedTreesBenchmark`;
- it is also the reproducibility code used for the synthetic benchmark reported in the paper.

The workflow is deliberately kept in one place:

**fixed synthetic data → hyperparameter search → best configuration → recovery evaluation → unseen inference → F/C/P**

The benchmark module performs the actual model selection. The notebook does not manually rank configurations or reconstruct the selected model.

> **Important:** the synthetic corpora must be generated first with `datasetdemo.ipynb`. This notebook reuses those fixed datasets so every configuration is evaluated on exactly the same data.

## What is fixed and what can be changed?

This notebook uses the **default benchmark settings provided by `polartox.benchmark`**. These defaults give a ready-to-run starting point, but they are not required.

The main benchmark settings can be changed:

- **search space** — pass a dictionary defining the values to consider for each hyperparameter;
- **strategy** — `"full"` evaluates every configuration, while `"random"` samples configurations;
- **number of runs** — controls how many configurations are sampled with random search;
- **seed** — makes random search reproducible;
- **metrics** — choose which recovery metrics to calculate;
- **selection metric** — choose which metric determines the best configuration;
- **selection direction** — choose `"max"` or `"min"`;
- **pipeline settings** — dimensions, scale, and any fixed pipeline parameters.

For this notebook, the default search space, metrics, and selection metric are imported directly from the package. You can replace `DEFAULT_SEARCH_SPACE` with your own dictionary without changing the benchmark code.

Ground truth is required for recovery-based model selection. After the best configuration is selected, the resulting pipeline can be run **without ground truth**, which is the normal inference setting for real annotation data.

## 1. Imports and experiment settings

Only a small amount of configuration is needed here. The actual search, evaluation, ranking, and selection are delegated to `PolarizedTreesBenchmark`.

In [1]:
import json
import sys
from pathlib import Path

import pandas as pd

from polartox.benchmark import (
    PolarizedTreesBenchmark,
    DEFAULT_SEARCH_SPACE,
    DEFAULT_METRICS,
    DEFAULT_SELECTION_METRIC,
)
from polartox.pipeline import PolarizedTreesPipeline


# Locate the repository root.
CWD = Path.cwd().resolve()

if (CWD / "benchmark_config.py").exists():
    PROJECT_ROOT = CWD
elif (CWD.parent / "benchmark_config.py").exists():
    PROJECT_ROOT = CWD.parent
else:
    raise FileNotFoundError(
        "Could not locate project root. "
        "Run this notebook from the notebooks directory "
        "or the project root."
    )

if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))


from benchmark_config import (
    DIMS,
    SCALE,
    BENCHMARK_CORPORA,
    INFERENCE_CORPUS,
)


DATA_DIR = PROJECT_ROOT / "benchmark_data"
RESULTS_DIR = PROJECT_ROOT / "benchmark_results"

RESULTS_DIR.mkdir(parents=True, exist_ok=True)

# Paper settings.
N_RUNS = 800
SEED = 0

print("Project root:", PROJECT_ROOT)
print("Benchmark corpora:", BENCHMARK_CORPORA)
print("Inference corpus:", INFERENCE_CORPUS)
print("Random configurations:", N_RUNS)
print("Seed:", SEED)

Project root: C:\Users\swkra\OneDrive\Υπολογιστής\ερευνα\HumanModelAlign\polarizedtrees\benchmarks
Benchmark corpora: ['A_default', 'B_weak_signal', 'C_deep']
Inference corpus: inference_unseen
Random configurations: 800
Seed: 0

## 2. Load the fixed synthetic datasets

The first notebook generates these datasets once and stores both the annotations and the per-text ground truth.

Ground truth tells us which SCD dimensions actually generated the polarization. That makes recovery metrics possible and allows the benchmark to perform model selection.

The inference corpus is kept separate and is not used for selecting the configuration.

In [2]:
def load_corpus(name):
    dataset = pd.read_csv(
        DATA_DIR / f"{name}_dataset.csv"
    )

    with open(
        DATA_DIR / f"{name}_ground_truth.json",
        encoding="utf-8",
    ) as f:
        ground_truth = {
            int(text_id): value
            for text_id, value in json.load(f).items()
        }

    return dataset, ground_truth


corpora = {
    name: load_corpus(name)
    for name in BENCHMARK_CORPORA
}

inference_dataset, inference_ground_truth = load_corpus(
    INFERENCE_CORPUS
)


for name, (dataset, ground_truth) in corpora.items():
    print(
        f"{name}: "
        f"{dataset.shape[0]:,} annotations | "
        f"{dataset['text_id'].nunique()} texts | "
        f"{len(ground_truth)} ground-truth entries"
    )

print(
    f"{INFERENCE_CORPUS}: "
    f"{inference_dataset.shape[0]:,} annotations | "
    f"{inference_dataset['text_id'].nunique()} texts"
)

A_default: 162,000 annotations | 100 texts | 100 ground-truth entries
B_weak_signal: 162,000 annotations | 100 texts | 100 ground-truth entries
C_deep: 162,000 annotations | 100 texts | 100 ground-truth entries
inference_unseen: 162,000 annotations | 100 texts

## 3. Prepare the model-selection data

`PolarizedTreesBenchmark` works on one annotation dataset. We therefore combine A/B/C into one development corpus.

The text IDs are shifted so that the three corpora remain completely distinct. The three corpora contain the same number of texts, so their combined mean gives each corpus equal weight.

This is only a data-preparation step; it does not change the annotations or their ground truth.

In [3]:
text_counts = {
    name: dataset["text_id"].nunique()
    for name, (dataset, _) in corpora.items()
}

if len(set(text_counts.values())) != 1:
    raise ValueError(
        "A/B/C must contain the same number of texts "
        "for equal-weight mean Jaccard."
    )


benchmark_parts = []
benchmark_ground_truth = {}
text_groups = {}

offset = 0

for corpus_name in BENCHMARK_CORPORA:
    dataset, ground_truth = corpora[corpus_name]

    part = dataset.copy()

    text_ids = sorted(
        part["text_id"].unique()
    )

    id_map = {
        old_id: offset + i
        for i, old_id in enumerate(text_ids)
    }

    part["text_id"] = part["text_id"].map(id_map)

    benchmark_parts.append(part)

    for old_id, config in ground_truth.items():
        benchmark_ground_truth[
            id_map[old_id]
        ] = config

    for new_id in id_map.values():
        text_groups[new_id] = corpus_name

    offset += len(text_ids)


benchmark_dataset = pd.concat(
    benchmark_parts,
    ignore_index=True,
)

print("Combined annotations:", benchmark_dataset.shape)
print("Combined texts:", benchmark_dataset["text_id"].nunique())
print("Ground-truth entries:", len(benchmark_ground_truth))

Combined annotations: (486000, 8)
Combined texts: 300
Ground-truth entries: 300

## 4. Define the paper's search space

For the paper, we consider the full valid search space of 3,240 configurations.

The space is written as explicit configurations rather than a simple Cartesian product because `beta` is meaningful only when `variant="beta"`.

For a smaller demonstration, this cell can be replaced by a small custom search space. The benchmark API supports both forms.

In [4]:
SEARCH_SPACE = DEFAULT_SEARCH_SPACE.copy()

print("Search space:")
for parameter, values in SEARCH_SPACE.items():
    print(f"  {parameter}: {values}")

n_configurations = 1
for values in SEARCH_SPACE.values():
    n_configurations *= len(values)

print("\nTotal possible configurations:", n_configurations)

Search space:
  theta_filter: [0.2, 0.3, 0.4]
  min_size_frac: [0.02, 0.03, 0.05]
  max_depth: [4, 6, 8]
  variant: ['max', 'var', 'beta']
  h: [0.05, 0.1, 0.15, 0.2]
  relative_h: [False, True]
  theta_stop: [0.05, 0.1, 0.15]

Total possible configurations: 1944

## 5. Create the base Polarized Trees pipeline

The user provides **one pipeline object** to the benchmark.

The benchmark uses its settings as the base and creates candidate pipelines internally while testing configurations. After model selection, the selected pipeline is available directly through `benchmark.get_best_pipeline()`.

The user therefore does not need to manually reconstruct the winning pipeline.

In [5]:
# theta_filter, h and max_depth are required by the pipeline; the
# benchmark overrides all of them with each searched configuration,
# so these are placeholders.
pipeline = PolarizedTreesPipeline(
    dims=DIMS,
    scale=SCALE,
    theta_filter=0.3,
    h=0.10,
    max_depth=6,
)

print(pipeline)

<polartox.pipeline.PolarizedTreesPipeline object at 0x000002842C74ACF0>

## 6. Run model selection

This is the main benchmark step.

The benchmark:

1. generates the configurations from the supplied search-space dictionary;
2. evaluates the requested configurations on the same annotations and ground truth;
3. computes the requested recovery metrics;
4. ranks the configurations using the selected metric;
5. stores the best configuration and the corresponding pipeline.

Here we use random search so that the same notebook can also demonstrate the `random` strategy. For a small search space, `strategy="full"` is useful because it evaluates every possible configuration.

The defaults are imported from the package, but all of these choices can be changed.

In [6]:
benchmark = PolarizedTreesBenchmark(
    pipeline=pipeline,
    annotations=benchmark_dataset,
    ground_truth=benchmark_ground_truth,

    # Corpus of every text: metrics and statistics are computed per
    # corpus and then averaged over corpora.
    text_groups=text_groups,

    # Paper search.
    search_space=SEARCH_SPACE,
    strategy="random",
    n_runs=N_RUNS,
    seed=SEED,

    # Recovery metrics available in the synthetic setting.
    metrics=DEFAULT_METRICS,

    # Paper selection criterion.
    selection_metric=DEFAULT_SELECTION_METRIC,

    # Keep the highest score.
    selection_direction="max",

    top_k=20,
    verbose=True,

    # Save progress every 50 configurations; re-running this cell
    # after a crash resumes from the last checkpoint.
    checkpoint_dir=RESULTS_DIR / "checkpoint",
    checkpoint_every=50,

    # Evaluate configurations in parallel worker processes. Each worker
    # holds its own copy of the data (~150 MB); lower this if memory is tight.
    n_jobs=6,
)

benchmark.run()

[1/800] jaccard=0.7619
[2/800] jaccard=0.4231
[3/800] jaccard=0.8382
[4/800] jaccard=0.7439
[5/800] jaccard=0.8050
[6/800] jaccard=0.8720
[7/800] jaccard=0.8293
[8/800] jaccard=0.5178
[9/800] jaccard=0.8272
[10/800] jaccard=0.8382
[11/800] jaccard=0.8384
[12/800] jaccard=0.8414
[13/800] jaccard=0.8354
[14/800] jaccard=0.8691
[15/800] jaccard=0.8075
[16/800] jaccard=0.8154
[17/800] jaccard=0.5224
[18/800] jaccard=0.6666
[19/800] jaccard=0.8166
[20/800] jaccard=0.8298
[21/800] jaccard=0.8200
[22/800] jaccard=0.5328
[23/800] jaccard=0.8575
[24/800] jaccard=0.8288
[25/800] jaccard=0.8115
[26/800] jaccard=0.7879
[27/800] jaccard=0.8128
[28/800] jaccard=0.6950
[29/800] jaccard=0.8258
[30/800] jaccard=0.7790
[31/800] jaccard=0.6368
[32/800] jaccard=0.8436
[33/800] jaccard=0.8209
[34/800] jaccard=0.8200
[35/800] jaccard=0.8457
[36/800] jaccard=0.8282
[37/800] jaccard=0.5178
[38/800] jaccard=0.8185
[39/800] jaccard=0.6297
[40/800] jaccard=0.4694
[41/800] jaccard=0.8333
[42/800] jaccard=0.4694
[43/800] jaccard=0.7681
[44/800] jaccard=0.8209
[45/800] jaccard=0.8273
[46/800] jaccard=0.7985
[47/800] jaccard=0.7424
[48/800] jaccard=0.8419
[49/800] jaccard=0.8378
[50/800] jaccard=0.8231
Checkpoint saved at 50/800.
[51/800] jaccard=0.7341
[52/800] jaccard=0.5940
[53/800] jaccard=0.8176
[54/800] jaccard=0.4481
[55/800] jaccard=0.6368
[56/800] jaccard=0.8021
[57/800] jaccard=0.8309
[58/800] jaccard=0.4996
[59/800] jaccard=0.6942
[60/800] jaccard=0.6861
[61/800] jaccard=0.8088
[62/800] jaccard=0.8344
[63/800] jaccard=0.8279
[64/800] jaccard=0.7574
[65/800] jaccard=0.7569
[66/800] jaccard=0.6766
[67/800] jaccard=0.5885
[68/800] jaccard=0.7648
[69/800] jaccard=0.5114
[70/800] jaccard=0.4770
[71/800] jaccard=0.6832
[72/800] jaccard=0.8349
[73/800] jaccard=0.8378
[74/800] jaccard=0.8076
[75/800] jaccard=0.8078
[76/800] jaccard=0.8595
[77/800] jaccard=0.8296
[78/800] jaccard=0.6949
[79/800] jaccard=0.6414
[80/800] jaccard=0.8792
[81/800] jaccard=0.7922
[82/800] jaccard=0.6611
[83/800] jaccard=0.8621
[84/800] jaccard=0.8382
[85/800] jaccard=0.8678
[86/800] jaccard=0.8630
[87/800] jaccard=0.7950
[88/800] jaccard=0.8625
[89/800] jaccard=0.7888
[90/800] jaccard=0.5178
[91/800] jaccard=0.8210
[92/800] jaccard=0.7424
[93/800] jaccard=0.8186
[94/800] jaccard=0.8074
[95/800] jaccard=0.5178
[96/800] jaccard=0.8365
[97/800] jaccard=0.6490
[98/800] jaccard=0.8172
[99/800] jaccard=0.7664
[100/800] jaccard=0.7927
Checkpoint saved at 100/800.
[101/800] jaccard=0.6823
[102/800] jaccard=0.7424
[103/800] jaccard=0.8354
[104/800] jaccard=0.8528
[105/800] jaccard=0.7600
[106/800] jaccard=0.6475
[107/800] jaccard=0.8317
[108/800] jaccard=0.8488
[109/800] jaccard=0.7909
[110/800] jaccard=0.4641
[111/800] jaccard=0.8756
[112/800] jaccard=0.8340
[113/800] jaccard=0.7928
[114/800] jaccard=0.8600
[115/800] jaccard=0.4231
[116/800] jaccard=0.8751
[117/800] jaccard=0.6810
[118/800] jaccard=0.8382
[119/800] jaccard=0.4481
[120/800] jaccard=0.8190
[121/800] jaccard=0.8170
[122/800] jaccard=0.6590
[123/800] jaccard=0.7881
[124/800] jaccard=0.6478
[125/800] jaccard=0.8328
[126/800] jaccard=0.7727
[127/800] jaccard=0.8529
[128/800] jaccard=0.4231
[129/800] jaccard=0.7847
[130/800] jaccard=0.7513
[131/800] jaccard=0.6590
[132/800] jaccard=0.4770
[133/800] jaccard=0.8309
[134/800] jaccard=0.8448
[135/800] jaccard=0.8436
[136/800] jaccard=0.6666
[137/800] jaccard=0.8501
[138/800] jaccard=0.7948
[139/800] jaccard=0.8766
[140/800] jaccard=0.7431
[141/800] jaccard=0.8068
[142/800] jaccard=0.4917
[143/800] jaccard=0.8785
[144/800] jaccard=0.8331
[145/800] jaccard=0.8170
[146/800] jaccard=0.5350
[147/800] jaccard=0.7585
[148/800] jaccard=0.8016
[149/800] jaccard=0.8174
[150/800] jaccard=0.7974
Checkpoint saved at 150/800.
[151/800] jaccard=0.5885
[152/800] jaccard=0.8918
[153/800] jaccard=0.5152
[154/800] jaccard=0.6242
[155/800] jaccard=0.8286
[156/800] jaccard=0.8240
[157/800] jaccard=0.7912
[158/800] jaccard=0.8174
[159/800] jaccard=0.6414
[160/800] jaccard=0.8258
[161/800] jaccard=0.8226
[162/800] jaccard=0.7950
[163/800] jaccard=0.8365
[164/800] jaccard=0.8171
[165/800] jaccard=0.4917
[166/800] jaccard=0.8075
[167/800] jaccard=0.6000
[168/800] jaccard=0.8143
[169/800] jaccard=0.8368
[170/800] jaccard=0.7923
[171/800] jaccard=0.8478
[172/800] jaccard=0.8816
[173/800] jaccard=0.8544
[174/800] jaccard=0.7984
[175/800] jaccard=0.8279
[176/800] jaccard=0.8240
[177/800] jaccard=0.8317
[178/800] jaccard=0.7977
[179/800] jaccard=0.8368
[180/800] jaccard=0.7923
[181/800] jaccard=0.8600
[182/800] jaccard=0.8137
[183/800] jaccard=0.8333
[184/800] jaccard=0.4893
[185/800] jaccard=0.8217
[186/800] jaccard=0.8235
[187/800] jaccard=0.8186
[188/800] jaccard=0.4689
[189/800] jaccard=0.7984
[190/800] jaccard=0.8149
[191/800] jaccard=0.5152
[192/800] jaccard=0.4770
[193/800] jaccard=0.6038
[194/800] jaccard=0.8575
[195/800] jaccard=0.7975
[196/800] jaccard=0.4720
[197/800] jaccard=0.8216
[198/800] jaccard=0.5188
[199/800] jaccard=0.8775
[200/800] jaccard=0.8123
Checkpoint saved at 200/800.
[201/800] jaccard=0.7946
[202/800] jaccard=0.8550
[203/800] jaccard=0.8115
[204/800] jaccard=0.7896
[205/800] jaccard=0.8617
[206/800] jaccard=0.8210
[207/800] jaccard=0.8552
[208/800] jaccard=0.6616
[209/800] jaccard=0.7623
[210/800] jaccard=0.8756
[211/800] jaccard=0.7970
[212/800] jaccard=0.8324
[213/800] jaccard=0.4971
[214/800] jaccard=0.7763
[215/800] jaccard=0.8303
[216/800] jaccard=0.4689
[217/800] jaccard=0.7860
[218/800] jaccard=0.8678
[219/800] jaccard=0.5152
[220/800] jaccard=0.8472
[221/800] jaccard=0.7835
[222/800] jaccard=0.8539
[223/800] jaccard=0.8499
[224/800] jaccard=0.8123
[225/800] jaccard=0.8128
[226/800] jaccard=0.6000
[227/800] jaccard=0.8729
[228/800] jaccard=0.8362
[229/800] jaccard=0.4689
[230/800] jaccard=0.7481
[231/800] jaccard=0.6766
[232/800] jaccard=0.7773
[233/800] jaccard=0.8119
[234/800] jaccard=0.8046
[235/800] jaccard=0.8775
[236/800] jaccard=0.7773
[237/800] jaccard=0.8027
[238/800] jaccard=0.8405
[239/800] jaccard=0.8709
[240/800] jaccard=0.7587
[241/800] jaccard=0.7489
[242/800] jaccard=0.8016
[243/800] jaccard=0.8263
[244/800] jaccard=0.6597
[245/800] jaccard=0.8678
[246/800] jaccard=0.7493
[247/800] jaccard=0.8298
[248/800] jaccard=0.8364
[249/800] jaccard=0.4770
[250/800] jaccard=0.8020
Checkpoint saved at 250/800.
[251/800] jaccard=0.7525
[252/800] jaccard=0.8888
[253/800] jaccard=0.8006
[254/800] jaccard=0.7728
[255/800] jaccard=0.8517
[256/800] jaccard=0.8128
[257/800] jaccard=0.7639
[258/800] jaccard=0.8404
[259/800] jaccard=0.8728
[260/800] jaccard=0.8110
[261/800] jaccard=0.4231
[262/800] jaccard=0.4741
[263/800] jaccard=0.8244
[264/800] jaccard=0.6597
[265/800] jaccard=0.7885
[266/800] jaccard=0.7754
[267/800] jaccard=0.8328
[268/800] jaccard=0.7790
[269/800] jaccard=0.8617
[270/800] jaccard=0.4689
[271/800] jaccard=0.8372
[272/800] jaccard=0.7619
[273/800] jaccard=0.7844
[274/800] jaccard=0.8154
[275/800] jaccard=0.8059
[276/800] jaccard=0.7950
[277/800] jaccard=0.7493
[278/800] jaccard=0.4481
[279/800] jaccard=0.8204
[280/800] jaccard=0.7975
[281/800] jaccard=0.7991
[282/800] jaccard=0.5789
[283/800] jaccard=0.8127
[284/800] jaccard=0.8222
[285/800] jaccard=0.8076
[286/800] jaccard=0.7341
[287/800] jaccard=0.7947
[288/800] jaccard=0.8126
[289/800] jaccard=0.8335
[290/800] jaccard=0.8243
[291/800] jaccard=0.8549
[292/800] jaccard=0.8368
[293/800] jaccard=0.8698
[294/800] jaccard=0.7946
[295/800] jaccard=0.7481
[296/800] jaccard=0.8552
[297/800] jaccard=0.5350
[298/800] jaccard=0.8236
[299/800] jaccard=0.8620
[300/800] jaccard=0.8646
Checkpoint saved at 300/800.
[301/800] jaccard=0.4971
[302/800] jaccard=0.8587
[303/800] jaccard=0.7439
[304/800] jaccard=0.8183
[305/800] jaccard=0.7748
[306/800] jaccard=0.7525
[307/800] jaccard=0.8282
[308/800] jaccard=0.5586
[309/800] jaccard=0.7481
[310/800] jaccard=0.6984
[311/800] jaccard=0.7637
[312/800] jaccard=0.7469
[313/800] jaccard=0.8278
[314/800] jaccard=0.8655
[315/800] jaccard=0.8727
[316/800] jaccard=0.8045
[317/800] jaccard=0.8011
[318/800] jaccard=0.8119
[319/800] jaccard=0.5586
[320/800] jaccard=0.4971
[321/800] jaccard=0.8775
[322/800] jaccard=0.8345
[323/800] jaccard=0.8001
[324/800] jaccard=0.8282
[325/800] jaccard=0.8016
[326/800] jaccard=0.8596
[327/800] jaccard=0.8349
[328/800] jaccard=0.6841
[329/800] jaccard=0.8539
[330/800] jaccard=0.8243
[331/800] jaccard=0.8399
[332/800] jaccard=0.8068
[333/800] jaccard=0.8410
[334/800] jaccard=0.7933
[335/800] jaccard=0.8503
[336/800] jaccard=0.8488
[337/800] jaccard=0.4481
[338/800] jaccard=0.8282
[339/800] jaccard=0.5107
[340/800] jaccard=0.7926
[341/800] jaccard=0.5361
[342/800] jaccard=0.8277
[343/800] jaccard=0.8267
[344/800] jaccard=0.8020
[345/800] jaccard=0.8183
[346/800] jaccard=0.5224
[347/800] jaccard=0.7915
[348/800] jaccard=0.5152
[349/800] jaccard=0.8378
[350/800] jaccard=0.7483
Checkpoint saved at 350/800.
[351/800] jaccard=0.7951
[352/800] jaccard=0.8534
[353/800] jaccard=0.8263
[354/800] jaccard=0.5350
[355/800] jaccard=0.8322
[356/800] jaccard=0.5133
[357/800] jaccard=0.8327
[358/800] jaccard=0.7869
[359/800] jaccard=0.4996
[360/800] jaccard=0.8453
[361/800] jaccard=0.8343
[362/800] jaccard=0.8404
[363/800] jaccard=0.8271
[364/800] jaccard=0.8756
[365/800] jaccard=0.8216
[366/800] jaccard=0.8122
[367/800] jaccard=0.8226
[368/800] jaccard=0.5069
[369/800] jaccard=0.8399
[370/800] jaccard=0.8383
[371/800] jaccard=0.7844
[372/800] jaccard=0.4742
[373/800] jaccard=0.8457
[374/800] jaccard=0.8509
[375/800] jaccard=0.6766
[376/800] jaccard=0.8624
[377/800] jaccard=0.8244
[378/800] jaccard=0.8320
[379/800] jaccard=0.6297
[380/800] jaccard=0.5140
[381/800] jaccard=0.8001
[382/800] jaccard=0.7623
[383/800] jaccard=0.7931
[384/800] jaccard=0.7780
[385/800] jaccard=0.5178
[386/800] jaccard=0.4231
[387/800] jaccard=0.7958
[388/800] jaccard=0.6637
[389/800] jaccard=0.8542
[390/800] jaccard=0.7702
[391/800] jaccard=0.6597
[392/800] jaccard=0.7483
[393/800] jaccard=0.7844
[394/800] jaccard=0.5224
[395/800] jaccard=0.8403
[396/800] jaccard=0.8286
[397/800] jaccard=0.8632
[398/800] jaccard=0.8409
[399/800] jaccard=0.8128
[400/800] jaccard=0.8622
Checkpoint saved at 400/800.
[401/800] jaccard=0.5350
[402/800] jaccard=0.8288
[403/800] jaccard=0.8382
[404/800] jaccard=0.7510
[405/800] jaccard=0.7926
[406/800] jaccard=0.8382
[407/800] jaccard=0.8064
[408/800] jaccard=0.8756
[409/800] jaccard=0.7941
[410/800] jaccard=0.8048
[411/800] jaccard=0.7654
[412/800] jaccard=0.8596
[413/800] jaccard=0.8023
[414/800] jaccard=0.5361
[415/800] jaccard=0.7455
[416/800] jaccard=0.6493
[417/800] jaccard=0.8020
[418/800] jaccard=0.6977
[419/800] jaccard=0.4996
[420/800] jaccard=0.8001
[421/800] jaccard=0.8001
[422/800] jaccard=0.7748
[423/800] jaccard=0.7969
[424/800] jaccard=0.7801
[425/800] jaccard=0.7885
[426/800] jaccard=0.8035
[427/800] jaccard=0.8625
[428/800] jaccard=0.8404
[429/800] jaccard=0.8549
[430/800] jaccard=0.4893
[431/800] jaccard=0.8698
[432/800] jaccard=0.7418
[433/800] jaccard=0.8149
[434/800] jaccard=0.7779
[435/800] jaccard=0.6958
[436/800] jaccard=0.6625
[437/800] jaccard=0.8490
[438/800] jaccard=0.8463
[439/800] jaccard=0.8693
[440/800] jaccard=0.8126
[441/800] jaccard=0.8351
[442/800] jaccard=0.8032
[443/800] jaccard=0.4481
[444/800] jaccard=0.8046
[445/800] jaccard=0.8368
[446/800] jaccard=0.8072
[447/800] jaccard=0.4971
[448/800] jaccard=0.8398
[449/800] jaccard=0.8096
[450/800] jaccard=0.8160
Checkpoint saved at 450/800.
[451/800] jaccard=0.8343
[452/800] jaccard=0.6616
[453/800] jaccard=0.8785
[454/800] jaccard=0.7947
[455/800] jaccard=0.8004
[456/800] jaccard=0.8202
[457/800] jaccard=0.8397
[458/800] jaccard=0.8574
[459/800] jaccard=0.7835
[460/800] jaccard=0.8288
[461/800] jaccard=0.8490
[462/800] jaccard=0.6570
[463/800] jaccard=0.6038
[464/800] jaccard=0.5328
[465/800] jaccard=0.8164
[466/800] jaccard=0.8326
[467/800] jaccard=0.8059
[468/800] jaccard=0.8293
[469/800] jaccard=0.5328
[470/800] jaccard=0.7829
[471/800] jaccard=0.7833
[472/800] jaccard=0.8459
[473/800] jaccard=0.8731
[474/800] jaccard=0.8552
[475/800] jaccard=0.8330
[476/800] jaccard=0.7985
[477/800] jaccard=0.4742
[478/800] jaccard=0.7785
[479/800] jaccard=0.8128
[480/800] jaccard=0.8327
[481/800] jaccard=0.8382
[482/800] jaccard=0.7754
[483/800] jaccard=0.8410
[484/800] jaccard=0.6823
[485/800] jaccard=0.7720
[486/800] jaccard=0.8596
[487/800] jaccard=0.6000
[488/800] jaccard=0.8263
[489/800] jaccard=0.8178
[490/800] jaccard=0.8246
[491/800] jaccard=0.6604
[492/800] jaccard=0.8543
[493/800] jaccard=0.7927
[494/800] jaccard=0.5214
[495/800] jaccard=0.7958
[496/800] jaccard=0.8320
[497/800] jaccard=0.8488
[498/800] jaccard=0.8226
[499/800] jaccard=0.6649
[500/800] jaccard=0.4231
Checkpoint saved at 500/800.
[501/800] jaccard=0.8785
[502/800] jaccard=0.4741
[503/800] jaccard=0.8100
[504/800] jaccard=0.7527
[505/800] jaccard=0.7744
[506/800] jaccard=0.8166
[507/800] jaccard=0.8625
[508/800] jaccard=0.8185
[509/800] jaccard=0.5703
[510/800] jaccard=0.6414
[511/800] jaccard=0.7971
[512/800] jaccard=0.6984
[513/800] jaccard=0.5940
[514/800] jaccard=0.5140
[515/800] jaccard=0.8405
[516/800] jaccard=0.7970
[517/800] jaccard=0.8180
[518/800] jaccard=0.4694
[519/800] jaccard=0.6512
[520/800] jaccard=0.5703
[521/800] jaccard=0.7928
[522/800] jaccard=0.8792
[523/800] jaccard=0.8410
[524/800] jaccard=0.8096
[525/800] jaccard=0.8338
[526/800] jaccard=0.6611
[527/800] jaccard=0.6810
[528/800] jaccard=0.7525
[529/800] jaccard=0.8283
[530/800] jaccard=0.4770
[531/800] jaccard=0.8543
[532/800] jaccard=0.6666
[533/800] jaccard=0.7835
[534/800] jaccard=0.8016
[535/800] jaccard=0.7790
[536/800] jaccard=0.7983
[537/800] jaccard=0.6949
[538/800] jaccard=0.8539
[539/800] jaccard=0.8243
[540/800] jaccard=0.8126
[541/800] jaccard=0.8431
[542/800] jaccard=0.8051
[543/800] jaccard=0.8183
[544/800] jaccard=0.8096
[545/800] jaccard=0.7859
[546/800] jaccard=0.7686
[547/800] jaccard=0.7574
[548/800] jaccard=0.8547
[549/800] jaccard=0.8035
[550/800] jaccard=0.8574
Checkpoint saved at 550/800.
[551/800] jaccard=0.8418
[552/800] jaccard=0.7639
[553/800] jaccard=0.5361
[554/800] jaccard=0.7881
[555/800] jaccard=0.8115
[556/800] jaccard=0.7720
[557/800] jaccard=0.8709
[558/800] jaccard=0.6597
[559/800] jaccard=0.7951
[560/800] jaccard=0.8552
[561/800] jaccard=0.8309
[562/800] jaccard=0.7869
[563/800] jaccard=0.7792
[564/800] jaccard=0.8888
[565/800] jaccard=0.4481
[566/800] jaccard=0.7907
[567/800] jaccard=0.7927
[568/800] jaccard=0.6496
[569/800] jaccard=0.7850
[570/800] jaccard=0.8673
[571/800] jaccard=0.7928
[572/800] jaccard=0.8298
[573/800] jaccard=0.7418
[574/800] jaccard=0.8539
[575/800] jaccard=0.7982
[576/800] jaccard=0.8483
[577/800] jaccard=0.8345
[578/800] jaccard=0.8037
[579/800] jaccard=0.5448
[580/800] jaccard=0.8067
[581/800] jaccard=0.6236
[582/800] jaccard=0.6616
[583/800] jaccard=0.7896
[584/800] jaccard=0.8185
[585/800] jaccard=0.8170
[586/800] jaccard=0.8164
[587/800] jaccard=0.8217
[588/800] jaccard=0.8670
[589/800] jaccard=0.8186
[590/800] jaccard=0.6666
[591/800] jaccard=0.4741
[592/800] jaccard=0.8166
[593/800] jaccard=0.4720
[594/800] jaccard=0.8015
[595/800] jaccard=0.8085
[596/800] jaccard=0.8085
[597/800] jaccard=0.8587
[598/800] jaccard=0.7754
[599/800] jaccard=0.8100
[600/800] jaccard=0.8436
Checkpoint saved at 600/800.
[601/800] jaccard=0.8317
[602/800] jaccard=0.7639
[603/800] jaccard=0.7784
[604/800] jaccard=0.8410
[605/800] jaccard=0.7888
[606/800] jaccard=0.8693
[607/800] jaccard=0.8340
[608/800] jaccard=0.7915
[609/800] jaccard=0.8362
[610/800] jaccard=0.6000
[611/800] jaccard=0.8277
[612/800] jaccard=0.8094
[613/800] jaccard=0.5350
[614/800] jaccard=0.8228
[615/800] jaccard=0.4741
[616/800] jaccard=0.8280
[617/800] jaccard=0.8015
[618/800] jaccard=0.8412
[619/800] jaccard=0.4720
[620/800] jaccard=0.8059
[621/800] jaccard=0.4231
[622/800] jaccard=0.7452
[623/800] jaccard=0.7824
[624/800] jaccard=0.4770
[625/800] jaccard=0.6038
[626/800] jaccard=0.7915
[627/800] jaccard=0.8075
[628/800] jaccard=0.8345
[629/800] jaccard=0.7933
[630/800] jaccard=0.8220
[631/800] jaccard=0.8188
[632/800] jaccard=0.7574
[633/800] jaccard=0.7844
[634/800] jaccard=0.8691
[635/800] jaccard=0.6637
[636/800] jaccard=0.7483
[637/800] jaccard=0.8015
[638/800] jaccard=0.8754
[639/800] jaccard=0.7829
[640/800] jaccard=0.8462
[641/800] jaccard=0.8045
[642/800] jaccard=0.5703
[643/800] jaccard=0.6000
[644/800] jaccard=0.7790
[645/800] jaccard=0.7878
[646/800] jaccard=0.5338
[647/800] jaccard=0.8087
[648/800] jaccard=0.7221
[649/800] jaccard=0.8366
[650/800] jaccard=0.7679
Checkpoint saved at 650/800.
[651/800] jaccard=0.7639
[652/800] jaccard=0.7824
[653/800] jaccard=0.8050
[654/800] jaccard=0.8165
[655/800] jaccard=0.8528
[656/800] jaccard=0.8751
[657/800] jaccard=0.7637
[658/800] jaccard=0.7982
[659/800] jaccard=0.8397
[660/800] jaccard=0.8050
[661/800] jaccard=0.4720
[662/800] jaccard=0.8046
[663/800] jaccard=0.5224
[664/800] jaccard=0.7682
[665/800] jaccard=0.8170
[666/800] jaccard=0.4720
[667/800] jaccard=0.8309
[668/800] jaccard=0.8263
[669/800] jaccard=0.8173
[670/800] jaccard=0.8216
[671/800] jaccard=0.6618
[672/800] jaccard=0.6984
[673/800] jaccard=0.8066
[674/800] jaccard=0.8276
[675/800] jaccard=0.8001
[676/800] jaccard=0.8303
[677/800] jaccard=0.8136
[678/800] jaccard=0.8342
[679/800] jaccard=0.8282
[680/800] jaccard=0.5188
[681/800] jaccard=0.8721
[682/800] jaccard=0.8188
[683/800] jaccard=0.8128
[684/800] jaccard=0.8509
[685/800] jaccard=0.4481
[686/800] jaccard=0.7481
[687/800] jaccard=0.4741
[688/800] jaccard=0.4741
[689/800] jaccard=0.8382
[690/800] jaccard=0.7933
[691/800] jaccard=0.4720
[692/800] jaccard=0.8538
[693/800] jaccard=0.8322
[694/800] jaccard=0.6242
[695/800] jaccard=0.8072
[696/800] jaccard=0.4481
[697/800] jaccard=0.7452
[698/800] jaccard=0.8166
[699/800] jaccard=0.8587
[700/800] jaccard=0.8368
Checkpoint saved at 700/800.
[701/800] jaccard=0.4917
[702/800] jaccard=0.5361
[703/800] jaccard=0.7953
[704/800] jaccard=0.8365
[705/800] jaccard=0.8539
[706/800] jaccard=0.4971
[707/800] jaccard=0.7475
[708/800] jaccard=0.8331
[709/800] jaccard=0.7953
[710/800] jaccard=0.8258
[711/800] jaccard=0.8254
[712/800] jaccard=0.6512
[713/800] jaccard=0.7974
[714/800] jaccard=0.8534
[715/800] jaccard=0.8230
[716/800] jaccard=0.7876
[717/800] jaccard=0.7623
[718/800] jaccard=0.7935
[719/800] jaccard=0.8405
[720/800] jaccard=0.6414
[721/800] jaccard=0.7754
[722/800] jaccard=0.7974
[723/800] jaccard=0.8544
[724/800] jaccard=0.8226
[725/800] jaccard=0.7928
[726/800] jaccard=0.8345
[727/800] jaccard=0.8522
[728/800] jaccard=0.4231
[729/800] jaccard=0.8404
[730/800] jaccard=0.7933
[731/800] jaccard=0.6649
[732/800] jaccard=0.4231
[733/800] jaccard=0.8343
[734/800] jaccard=0.7383
[735/800] jaccard=0.5178
[736/800] jaccard=0.8235
[737/800] jaccard=0.6841
[738/800] jaccard=0.8074
[739/800] jaccard=0.8326
[740/800] jaccard=0.4742
[741/800] jaccard=0.4231
[742/800] jaccard=0.6977
[743/800] jaccard=0.5214
[744/800] jaccard=0.5350
[745/800] jaccard=0.7639
[746/800] jaccard=0.8727
[747/800] jaccard=0.4742
[748/800] jaccard=0.8265
[749/800] jaccard=0.8460
[750/800] jaccard=0.8345
Checkpoint saved at 750/800.
[751/800] jaccard=0.6604
[752/800] jaccard=0.8414
[753/800] jaccard=0.8032
[754/800] jaccard=0.8220
[755/800] jaccard=0.6570
[756/800] jaccard=0.8575
[757/800] jaccard=0.8204
[758/800] jaccard=0.8045
[759/800] jaccard=0.8344
[760/800] jaccard=0.5586
[761/800] jaccard=0.8258
[762/800] jaccard=0.8625
[763/800] jaccard=0.7691
[764/800] jaccard=0.8399
[765/800] jaccard=0.8046
[766/800] jaccard=0.4996
[767/800] jaccard=0.8760
[768/800] jaccard=0.6958
[769/800] jaccard=0.6766
[770/800] jaccard=0.8760
[771/800] jaccard=0.8455
[772/800] jaccard=0.8082
[773/800] jaccard=0.8729
[774/800] jaccard=0.8282
[775/800] jaccard=0.7824
[776/800] jaccard=0.8340
[777/800] jaccard=0.6861
[778/800] jaccard=0.8727
[779/800] jaccard=0.8811
[780/800] jaccard=0.4720
[781/800] jaccard=0.7888
[782/800] jaccard=0.7939
[783/800] jaccard=0.8075
[784/800] jaccard=0.5566
[785/800] jaccard=0.5703
[786/800] jaccard=0.7847

## 7. Inspect the selected configuration

The benchmark now contains the complete model-selection result.

Nothing is selected manually here. These values are returned by the benchmark after ranking all evaluated configurations.

In [7]:
print("Best configuration:")
print(benchmark.get_best_config())

print("\nBest mean Jaccard:")
print(benchmark.get_best_score())

print("\nTop configurations:")
display(benchmark.get_top_configs())

Best configuration:
{'theta_filter': 0.3, 'min_size_frac': 0.03, 'max_depth': 4, 'variant': 'beta', 'beta': 1.0, 'h': 0.15, 'relative_h': True, 'theta_stop': 0.1}

Best mean Jaccard:
0.8917621987066432

Top configurations:

,rank,configuration_id,theta_filter,min_size_frac,max_depth,variant,beta,h,relative_h,theta_stop,...,precision_min,precision_max,recall,recall_median,recall_std,recall_q1,recall_q3,recall_min,recall_max,exact_match
0,1,152,0.3,0.03,4,beta,1.0,0.15,True,0.1,...,0.300000,1.0,0.931752,1.0,0.183839,0.916667,1.0,0.194444,1.0,0.747310
1,2,252,0.2,0.02,8,beta,1.0,0.15,True,0.1,...,0.300000,1.0,0.932267,1.0,0.182724,0.916667,1.0,0.194444,1.0,0.742754
2,3,564,0.2,0.02,4,beta,1.0,0.15,True,0.1,...,0.300000,1.0,0.932267,1.0,0.182724,0.916667,1.0,0.194444,1.0,0.742754
3,4,172,0.4,0.02,8,beta,1.0,0.15,True,0.1,...,0.300000,1.0,0.928151,1.0,0.185379,0.916667,1.0,0.194444,1.0,0.716428
4,5,779,0.3,0.02,4,beta,2.0,0.10,True,0.1,...,0.266667,1.0,0.934215,1.0,0.161052,0.916667,1.0,0.194444,1.0,0.712337
5,6,522,0.3,0.03,4,beta,0.5,0.20,True,0.1,...,0.222222,1.0,0.920742,1.0,0.204097,0.916667,1.0,0.083333,1.0,0.724043
6,7,80,0.3,0.02,4,beta,0.5,0.20,True,0.1,...,0.222222,1.0,0.920742,1.0,0.204097,0.916667,1.0,0.083333,1.0,0.724043
7,8,453,0.3,0.03,6,beta,1.0,0.10,True,0.1,...,0.266667,1.0,0.939946,1.0,0.159064,0.916667,1.0,0.194444,1.0,0.711500
8,9,143,0.3,0.02,8,beta,1.0,0.10,True,0.1,...,0.266667,1.0,0.939946,1.0,0.159064,0.916667,1.0,0.194444,1.0,0.711500
9,10,501,0.3,0.03,8,beta,1.0,0.10,True,0.1,...,0.266667,1.0,0.939946,1.0,0.159064,0.916667,1.0,0.194444,1.0,0.711500
10,11,235,0.2,0.02,4,beta,2.0,0.10,True,0.1,...,0.266667,1.0,0.934509,1.0,0.160336,0.916667,1.0,0.194444,1.0,0.708075
11,12,321,0.2,0.03,6,beta,2.0,0.10,True,0.1,...,0.266667,1.0,0.934509,1.0,0.160336,0.916667,1.0,0.194444,1.0,0.708075
12,13,199,0.2,0.02,8,beta,2.0,0.10,True,0.1,...,0.266667,1.0,0.934509,1.0,0.160336,0.916667,1.0,0.194444,1.0,0.708075
13,14,139,0.2,0.03,4,beta,0.5,0.20,True,0.1,...,0.222222,1.0,0.921440,1.0,0.202845,0.916667,1.0,0.083333,1.0,0.719634
14,15,767,0.3,0.03,6,beta,1.0,0.20,True,0.1,...,0.000000,1.0,0.900467,1.0,0.230364,0.916667,1.0,0.000000,1.0,0.733309
15,16,770,0.3,0.02,6,beta,1.0,0.20,True,0.1,...,0.000000,1.0,0.900467,1.0,0.230364,0.916667,1.0,0.000000,1.0,0.733309
16,17,111,0.2,0.03,6,beta,1.0,0.10,True,0.1,...,0.266667,1.0,0.940203,1.0,0.158358,0.916667,1.0,0.194444,1.0,0.707384
17,18,364,0.2,0.02,6,beta,1.0,0.10,True,0.1,...,0.266667,1.0,0.940203,1.0,0.158358,0.916667,1.0,0.194444,1.0,0.707384
18,19,210,0.2,0.03,4,beta,1.0,0.10,True,0.1,...,0.266667,1.0,0.940203,1.0,0.158358,0.916667,1.0,0.194444,1.0,0.707384
19,20,408,0.2,0.03,6,var,1.0,0.10,True,0.1,...,0.266667,1.0,0.930627,1.0,0.163146,0.916667,1.0,0.194444,1.0,0.704796

## 8. Inspect all benchmark results

The complete table contains one row per evaluated configuration.

This is useful for checking how sensitive performance is to the different hyperparameters and for reproducing the ranking reported in the paper.

In [8]:
results_df = benchmark.get_results()

print("Evaluated configurations:", len(results_df))

display(
    results_df.head(20)
)

Evaluated configurations: 800

,rank,configuration_id,theta_filter,min_size_frac,max_depth,variant,beta,h,relative_h,theta_stop,...,precision_min,precision_max,recall,recall_median,recall_std,recall_q1,recall_q3,recall_min,recall_max,exact_match
0,1,152,0.3,0.03,4,beta,1.0,0.15,True,0.1,...,0.300000,1.0,0.931752,1.0,0.183839,0.916667,1.0,0.194444,1.0,0.747310
1,2,252,0.2,0.02,8,beta,1.0,0.15,True,0.1,...,0.300000,1.0,0.932267,1.0,0.182724,0.916667,1.0,0.194444,1.0,0.742754
2,3,564,0.2,0.02,4,beta,1.0,0.15,True,0.1,...,0.300000,1.0,0.932267,1.0,0.182724,0.916667,1.0,0.194444,1.0,0.742754
3,4,172,0.4,0.02,8,beta,1.0,0.15,True,0.1,...,0.300000,1.0,0.928151,1.0,0.185379,0.916667,1.0,0.194444,1.0,0.716428
4,5,779,0.3,0.02,4,beta,2.0,0.10,True,0.1,...,0.266667,1.0,0.934215,1.0,0.161052,0.916667,1.0,0.194444,1.0,0.712337
5,6,522,0.3,0.03,4,beta,0.5,0.20,True,0.1,...,0.222222,1.0,0.920742,1.0,0.204097,0.916667,1.0,0.083333,1.0,0.724043
6,7,80,0.3,0.02,4,beta,0.5,0.20,True,0.1,...,0.222222,1.0,0.920742,1.0,0.204097,0.916667,1.0,0.083333,1.0,0.724043
7,8,453,0.3,0.03,6,beta,1.0,0.10,True,0.1,...,0.266667,1.0,0.939946,1.0,0.159064,0.916667,1.0,0.194444,1.0,0.711500
8,9,143,0.3,0.02,8,beta,1.0,0.10,True,0.1,...,0.266667,1.0,0.939946,1.0,0.159064,0.916667,1.0,0.194444,1.0,0.711500
9,10,501,0.3,0.03,8,beta,1.0,0.10,True,0.1,...,0.266667,1.0,0.939946,1.0,0.159064,0.916667,1.0,0.194444,1.0,0.711500
10,11,235,0.2,0.02,4,beta,2.0,0.10,True,0.1,...,0.266667,1.0,0.934509,1.0,0.160336,0.916667,1.0,0.194444,1.0,0.708075
11,12,321,0.2,0.03,6,beta,2.0,0.10,True,0.1,...,0.266667,1.0,0.934509,1.0,0.160336,0.916667,1.0,0.194444,1.0,0.708075
12,13,199,0.2,0.02,8,beta,2.0,0.10,True,0.1,...,0.266667,1.0,0.934509,1.0,0.160336,0.916667,1.0,0.194444,1.0,0.708075
13,14,139,0.2,0.03,4,beta,0.5,0.20,True,0.1,...,0.222222,1.0,0.921440,1.0,0.202845,0.916667,1.0,0.083333,1.0,0.719634
14,15,767,0.3,0.03,6,beta,1.0,0.20,True,0.1,...,0.000000,1.0,0.900467,1.0,0.230364,0.916667,1.0,0.000000,1.0,0.733309
15,16,770,0.3,0.02,6,beta,1.0,0.20,True,0.1,...,0.000000,1.0,0.900467,1.0,0.230364,0.916667,1.0,0.000000,1.0,0.733309
16,17,111,0.2,0.03,6,beta,1.0,0.10,True,0.1,...,0.266667,1.0,0.940203,1.0,0.158358,0.916667,1.0,0.194444,1.0,0.707384
17,18,364,0.2,0.02,6,beta,1.0,0.10,True,0.1,...,0.266667,1.0,0.940203,1.0,0.158358,0.916667,1.0,0.194444,1.0,0.707384
18,19,210,0.2,0.03,4,beta,1.0,0.10,True,0.1,...,0.266667,1.0,0.940203,1.0,0.158358,0.916667,1.0,0.194444,1.0,0.707384
19,20,408,0.2,0.03,6,var,1.0,0.10,True,0.1,...,0.266667,1.0,0.930627,1.0,0.163146,0.916667,1.0,0.194444,1.0,0.704796

## 9. Get the selected pipeline

The benchmark stores the winning pipeline itself.

This is the pipeline that should be used for the subsequent evaluation and inference steps. There is no need to instantiate another `PolarizedTreesPipeline` manually.

In [10]:
best_pipeline = benchmark.get_best_pipeline()

print(best_pipeline)

<polartox.pipeline.PolarizedTreesPipeline object at 0x000002842C8B7ED0>

## 10. Evaluate the selected configuration on A/B/C

Model selection was performed on the combined development data. We now report the selected configuration separately on the three benchmark distributions.

Because ground truth is available, we can report Jaccard, precision, recall, and exact match.

In [11]:
# Per-corpus recovery of the selected (rank 1) configuration:
# mean plus distribution statistics of the per-text values,
# and the average over corpora.
group_results = benchmark.get_group_results()

selected_recovery = group_results[group_results["rank"] == 1]
selected_recovery = selected_recovery[
    ["corpus", "n_texts_evaluated", *benchmark._value_columns()]
].reset_index(drop=True)

mean_row = benchmark.get_results().iloc[[0]][
    benchmark._value_columns()
].assign(corpus="Mean")

selected_recovery = pd.concat(
    [selected_recovery, mean_row],
    ignore_index=True,
)

display(selected_recovery)

,corpus,n_texts_evaluated,jaccard,jaccard_median,jaccard_std,jaccard_q1,jaccard_q3,jaccard_min,jaccard_max,precision,...,precision_min,precision_max,recall,recall_median,recall_std,recall_q1,recall_q3,recall_min,recall_max,exact_match
0,A_default,84.0,0.918651,1.0,0.171602,1.000000,1.0,0.333333,1.0,0.974206,...,0.5,1.0,0.944444,1.0,0.152694,1.000000,1.0,0.333333,1.0,0.797619
1,B_weak_signal,81.0,0.869136,1.0,0.248623,0.750000,1.0,0.000000,1.0,0.875309,...,0.0,1.0,0.956790,1.0,0.192801,1.000000,1.0,0.000000,1.0,0.716049
2,C_deep,92.0,0.887500,1.0,0.212040,0.750000,1.0,0.250000,1.0,0.993478,...,0.4,1.0,0.894022,1.0,0.206023,0.750000,1.0,0.250000,1.0,0.728261
3,Mean,NaN,0.891762,1.0,0.210755,0.833333,1.0,0.194444,1.0,0.947664,...,0.3,1.0,0.931752,1.0,0.183839,0.916667,1.0,0.194444,1.0,0.747310

## 11. Run inference without ground truth

This is the important transition from **validation** to **inference**.

The selected configuration is now fixed. We deliberately do not pass ground truth.

In this setting Polarized Trees reports the outputs that are available on real annotation data:

- **F** — dimension frequency across tree depths;
- **C** — subgroup pole consistency;
- **P** — subgroup polarization reduction;
- diagnostics describing the resulting trees and residual polarization.

The ground-truth recovery metrics are not part of this inference result.

In [12]:
inference_results = best_pipeline.run_full_evaluation(
    inference_dataset,
    ground_truth=None,
    verbose=True,
)

F = inference_results["F"]
C = inference_results["C"]
P = inference_results["P"]
diagnostics = inference_results["diagnostics"]


print("=== F: Dimension Frequency ===")
display(F)

print("=== C: Subgroup Pole Consistency ===")
display(C.head(10))

print("=== P: Subgroup PRG ===")
display(P.head(10))

print("=== Diagnostics ===")
display(
    pd.Series(
        diagnostics,
        name="value",
    )
)

=== diagnostics ===
  retention_rate: 0.86
  mean_leaves: 7.593023255813954
  mean_depth: 2.3169984686064318
  mean_residual_ndfu: 0.17932784484016107
  mean_top_split_prg: 0.4408721547050139
  indeterminate_rate: 0.006125574272588055
  dims_never_used: []
=== F: Dimension Frequency ===

depth         1   2   3
dim
age          16  22  21
education    17  29  20
gender       15  20  19
orientation  25  25  29
politics     13  25  27

=== C: Subgroup Pole Consistency ===

                                    n_s  frac_toxic  frac_civil
subgroup
((education, low),)                  13    0.461538    0.538462
((education, high),)                 12    0.500000    0.500000
((orientation, lgbtq+),)             12    0.500000    0.500000
((orientation, heterosexual),)       12    0.583333    0.416667
((education, medium),)               11    0.727273    0.272727
((politics, center),)                 8    0.500000    0.500000
((politics, left),)                   8    0.625000    0.375000
((politics, right),)                  7    0.714286    0.285714
((age, 25-50), (education, high))     6    0.500000    0.500000
((age, 25-50), (politics, center))    6    0.666667    0.333333

=== P: Subgroup PRG ===

                                                    n_s  mean_prg
subgroup
((age, >50), (gender, male), (orientation, lgbt...    2  0.679320
((age, >50), (education, high), (politics, left))     1  0.643634
((orientation, lgbtq+),)                             12  0.635337
((orientation, heterosexual),)                       12  0.632869
((education, low), (gender, non-binary), (polit...    1  0.623129
((education, low), (gender, non-binary), (polit...    1  0.623129
((education, low), (gender, female), (politics,...    1  0.608743
((education, low), (gender, female), (politics,...    1  0.608743
((education, low), (orientation, lgbtq+), (poli...    1  0.606818
((age, 25-50), (gender, female), (orientation, ...    3  0.576895

=== Diagnostics ===

retention_rate            0.86
mean_leaves           7.593023
mean_depth            2.316998
mean_residual_ndfu    0.179328
mean_top_split_prg    0.440872
indeterminate_rate    0.006126
dims_never_used             []
Name: value, dtype: object

## 12. Save the benchmark and inference results

The benchmark report records the search settings, selected configuration, score, and top configurations.

The additional files provide the paper-facing recovery and inference outputs.

In [13]:
# Complete benchmark outputs.
# One row per configuration (averaged over corpora).
benchmark.save_results(
    RESULTS_DIR / "benchmark_configuration_summary.csv"
)

# One row per configuration and corpus.
benchmark.save_group_results(
    RESULTS_DIR / "benchmark_results.csv"
)

# Raw per-text recovery values (for boxplots).
benchmark.save_text_results(
    RESULTS_DIR / "benchmark_text_results.csv"
)

# Full report: settings, search space, best config, top configurations.
benchmark.save_report(
    RESULTS_DIR / "benchmark_report.json"
)

# Top-ranked configurations as a table.
benchmark.get_top_configs().to_csv(
    RESULTS_DIR / "top_configurations.csv",
    index=False,
)


# Selected configuration and recovery on A/B/C.
with open(
    RESULTS_DIR / "selected_configuration.json",
    "w",
    encoding="utf-8",
) as f:
    json.dump(
        benchmark.get_best_config(),
        f,
        indent=2,
    )

selected_recovery.to_csv(
    RESULTS_DIR / "selected_configuration_recovery.csv",
    index=False,
)


# Ground-truth-free inference outputs.
F.to_csv(
    RESULTS_DIR / "fcp_F_dimension_frequency.csv"
)

C.to_csv(
    RESULTS_DIR / "fcp_C_pole_consistency.csv"
)

P.to_csv(
    RESULTS_DIR / "fcp_P_subgroup_prg.csv"
)

with open(
    RESULTS_DIR / "fcp_inference_diagnostics.json",
    "w",
    encoding="utf-8",
) as f:
    json.dump(
        benchmark._python_value(diagnostics),
        f,
        indent=2,
        ensure_ascii=False,
        default=str,
    )

# Optional: everything inference-related in one Excel workbook.
try:
    with pd.ExcelWriter(
        RESULTS_DIR / "fcp_inference_results.xlsx"
    ) as writer:
        F.to_excel(writer, sheet_name="F")
        C.to_excel(writer, sheet_name="C")
        P.to_excel(writer, sheet_name="P")
        pd.Series(diagnostics, name="value").to_frame().to_excel(
            writer, sheet_name="diagnostics"
        )
except ImportError:
    print("openpyxl not installed: skipped fcp_inference_results.xlsx")


print(
    "Saved results to:",
    RESULTS_DIR.resolve()
)

Saved results to: C:\Users\swkra\OneDrive\Υπολογιστής\ερευνα\HumanModelAlign\polarizedtrees\benchmarks\benchmark_results

## 13. Adapting this notebook to another experiment

The notebook uses the package defaults as a convenient starting point. The benchmark itself is deliberately configurable.

The main things to change are:

```text
search_space        → a dictionary of hyperparameter values to search
strategy            → "full" or "random"
n_runs              → number sampled for random search
seed                → reproducible random sampling
metrics             → recovery metrics to compute
selection_metric    → metric used to choose the winner
selection_direction → "max" or "min"
pipeline            → fixed dimensions, scale, and other settings
annotations         → your annotation dataset
ground_truth        → required for recovery-based model selection
```

For example, a custom search can be as simple as:

```python
SEARCH_SPACE = {
    "relative_h": [True],
    "h": [0.05, 0.10, 0.15],
    "max_depth": [4, 6],
}
```

You then pass that dictionary directly to `PolarizedTreesBenchmark`.

If you already have an annotation dataset, you can use it directly as long as it follows the expected annotation format. Synthetic data is only needed when you want known ground truth for objective recovery evaluation.

If you do not have ground truth, the benchmark cannot use recovery metrics for model selection. In that case, use `PolarizedTreesPipeline` directly in inference mode and interpret F/C/P and diagnostics.

## Next steps

1. Run `datasetdemo.ipynb` to generate the fixed synthetic datasets.
2. Run this notebook to benchmark configurations and select the best pipeline.
3. Inspect the saved benchmark and inference outputs.
4. For another experiment, change the search-space dictionary and/or benchmark settings and rerun.